
/*!
 * Module dependencies.
 */

var slice = require('sliced');
var EventEmitter = require('events').EventEmitter;

/**
 * Promise constructor.
 *
 * _NOTE: The success and failure event names can be overridden by setting `Promise.SUCCESS` and `Promise.FAILURE` respectively._
 *
 * @param {Function***REMOVED*** back a function that accepts `fn(err, ...){***REMOVED***` as signature
 * @inherits NodeJS EventEmitter http://nodejs.org/api/events.html#events_class_events_eventemitter
 * @event `reject`: Emits when the promise is rejected (event name may be overridden)
 * @event `fulfill`: Emits when the promise is fulfilled (event name may be overridden)
 * @api public
 */

function Promise (back) {
  this.emitted = {***REMOVED***;
  this.ended = false;
  if ('function' == typeof back)
    this.onResolve(back);
***REMOVED***

/*!
 * event names
 */

Promise.SUCCESS = 'fulfill';
Promise.FAILURE = 'reject';

/*!
 * Inherits from EventEmitter.
 */

Promise.prototype.__proto__ = EventEmitter.prototype;

/**
 * Adds `listener` to the `event`.
 *
 * If `event` is either the success or failure event and the event has already been emitted, the`listener` is called immediately and passed the results of the original emitted event.
 *
 * @param {String***REMOVED*** event
 * @param {Function***REMOVED*** callback
 * @return {Promise***REMOVED*** this
 * @api public
 */

Promise.prototype.on = function (event, callback) {
  if (this.emitted[event])
    callback.apply(this, this.emitted[event]);
  else
    EventEmitter.prototype.on.call(this, event, callback);

  return this;
***REMOVED***

/**
 * Keeps track of emitted events to run them on `on`.
 *
 * @api private
 */

Promise.prototype.emit = function (event) {
  // ensures a promise can't be fulfill() or reject() more than once
  var success = this.constructor.SUCCESS;
  var failure = this.constructor.FAILURE;

  if (event == success || event == failure) {
    if (this.emitted[success] || this.emitted[failure]) {
      return this;
    ***REMOVED***
    this.emitted[event] = slice(arguments, 1);
  ***REMOVED***

  return EventEmitter.prototype.emit.apply(this, arguments);
***REMOVED***

/**
 * Fulfills this promise with passed arguments.
 *
 * If this promise has already been fulfilled or rejected, no action is taken.
 *
 * @api public
 */

Promise.prototype.fulfill = function () {
  var args = slice(arguments);
  return this.emit.apply(this, [this.constructor.SUCCESS].concat(args));
***REMOVED***

/**
 * Rejects this promise with `reason`.
 *
 * If this promise has already been fulfilled or rejected, no action is taken.
 *
 * @api public
 * @param {Object|String***REMOVED*** reason
 * @return {Promise***REMOVED*** this
 */

Promise.prototype.reject = function (reason) {
  return this.emit(this.constructor.FAILURE, reason);
***REMOVED***

/**
 * Resolves this promise to a rejected state if `err` is passed or
 * fulfilled state if no `err` is passed.
 *
 * @param {Error***REMOVED*** [err] error or null
 * @param {Object***REMOVED*** [val] value to fulfill the promise with
 * @api public
 */

Promise.prototype.resolve = function (err, val) {
  if (err) return this.reject(err);
  return this.fulfill(val);
***REMOVED***

/**
 * Adds a listener to the SUCCESS event.
 *
 * @return {Promise***REMOVED*** this
 * @api public
 */

Promise.prototype.onFulfill = function (fn) {
  return this.on(this.constructor.SUCCESS, fn);
***REMOVED***

/**
 * Adds a listener to the FAILURE event.
 *
 * @return {Promise***REMOVED*** this
 * @api public
 */

Promise.prototype.onReject = function (fn) {
  return this.on(this.constructor.FAILURE, fn);
***REMOVED***

/**
 * Adds a single function as a listener to both SUCCESS and FAILURE.
 *
 * It will be executed with traditional node.js argument position:
 * function (err, args...) {***REMOVED***
 *
 * @param {Function***REMOVED*** fn
 * @return {Promise***REMOVED*** this
 */

Promise.prototype.onResolve = function (fn) {
  this.on(this.constructor.FAILURE, function(err){
    fn.call(this, err);
  ***REMOVED***);

  this.on(this.constructor.SUCCESS, function(){
    var args = slice(arguments);
    fn.apply(this, [null].concat(args));
  ***REMOVED***);

  return this;
***REMOVED***

/**
 * Creates a new promise and returns it. If `onFulfill` or
 * `onReject` are passed, they are added as SUCCESS/ERROR callbacks
 * to this promise after the nextTick.
 *
 * Conforms to [promises/A+](https://github.com/promises-aplus/promises-spec) specification. Read for more detail how to use this method.
 *
 * ####Example:
 *
 *     var p = new Promise;
 *     p.then(function (arg) {
 *       return arg + 1;
 *     ***REMOVED***).then(function (arg) {
 *       throw new Error(arg + ' is an error!');
 *     ***REMOVED***).then(null, function (err) {
 *       assert.ok(err instanceof Error);
 *       assert.equal('2 is an error', err.message);
 *     ***REMOVED***);
 *     p.complete(1);
 *
 * @see promises-A+ https://github.com/promises-aplus/promises-spec
 * @param {Function***REMOVED*** onFulFill
 * @param {Function***REMOVED*** onReject
 * @return {Promise***REMOVED*** newPromise
 */

Promise.prototype.then = function (onFulfill, onReject) {
  var self = this
    , retPromise = new Promise;

  function handler (fn) {
    return function handle (arg) {
      var val;

      try {
        val = fn(arg);
      ***REMOVED*** catch (err) {
        if (retPromise.ended) throw err;
        return retPromise.reject(err);
      ***REMOVED***

      if (val && 'function' == typeof val.then) {
        val.then(
            retPromise.fulfill.bind(retPromise)
          , retPromise.reject.bind(retPromise))
      ***REMOVED*** else {
        retPromise.fulfill(val);
      ***REMOVED***
    ***REMOVED***
  ***REMOVED***

  process.nextTick(function () {
    if ('function' == typeof onReject) {
      self.onReject(handler(onReject));
    ***REMOVED*** else {
      self.onReject(retPromise.reject.bind(retPromise));
    ***REMOVED***

    if ('function' == typeof onFulfill) {
      self.onFulfill(handler(onFulfill));
    ***REMOVED*** else {
      self.onFulfill(retPromise.fulfill.bind(retPromise));
    ***REMOVED***
  ***REMOVED***)

  return retPromise;
***REMOVED***

/**
 * Signifies that this promise was the last in a chain of `then()s`: if a handler passed to the call to `then` which produced this promise throws, the exception will go uncaught.
 *
 * ####Example:
 *
 *     var p = new Promise;
 *     p.then(function(){ throw new Error('shucks') ***REMOVED***);
 *     setTimeout(function () {
 *       p.fulfill();
 *       // error was caught and swallowed by the promise returned from
 *       // p.then(). we either have to always register handlers on
 *       // the returned promises or we can do the following...
 *     ***REMOVED***, 10);
 *
 *     // this time we use .end() which prevents catching thrown errors
 *     var p = new Promise;
 *     var p2 = p.then(function(){ throw new Error('shucks') ***REMOVED***).end(); // <--
 *     setTimeout(function () {
 *       p.fulfill(); // throws "shucks"
 *     ***REMOVED***, 10);
 *
 * @api public
 */

Promise.prototype.end = function () {
  this.ended = true;
***REMOVED***

/*!
 * Module exports.
 */

module.exports = Promise;
